### ISSUE TITLE
Using Linux

### ISSUE THREAD

**Issue by jans23** [SensorDots/PortMuxRTool#1]
First of all, I have no experience with .NET at all.

I would like to use this tool under Linux. According to [this statement](https://stackoverflow.com/a/38066011) .NET 4.5 can't be used on Linux. I assume this is also true for .NET 4.0 which is required by PortMuxRTool. What I did found for Linux is [.NET Core SDK 2.2](https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install). Perhaps, it would be required to port this software to .NET Core 2.2 to make it work under Linux? Any pointers how to make this work would be much appreciated.

**Comment by bleckers** [comment]
Hi Jans,

You should be able to run it with mono - https://www.mono-project.com/download/stable/#download-lin

Basically just install mono, then run the exe with: mono PortMuxRTool.exe

Let me know how you get on :)

**Comment by jans23** [comment]
Sounds good. But where can I download the exe from? This is why I tried building this tool at the first place.

**Comment by bleckers** [comment]
Ah! It's just under the Release directory - https://github.com/SensorDots/PortMuxRTool/tree/master/PortMuxRTool/bin/Release

**Comment by jans23** [comment]
PortMuxRTool runs now. :-) I selected the correct port (/dev/ttyUSB0) and pressed "Connect" on any of the buttons. It complains "Board 1: Port 1 - Could not connect to serial port!" Perhaps I have to choose some other options before connecting?

I do can access the board with "screen /dev/ttyUSB0" with the same user account successfully.

**Comment by bleckers** [comment]
Is there a port number listed under the serial port drop down box?

It should auto detect any ports connected, but they might have the Windowsesq naming convention (COMx).

**Comment by bleckers** [comment]
Oh wait, you said you selected the port. Which distro are you using? I might have to test it out.

**Comment by jans23** [comment]
I use Ubuntu Linux 18.04. The port (device) does show in the drop down menu. 
![Bildschirmfoto von 2019-08-16 10-02-11](https://user-images.githubusercontent.com/1450547/63152844-18852e80-c00d-11e9-920c-cda275412176.png)

**Comment by bleckers** [comment]
Cool. Give me a tick, I'll test it again in a couple of hours :)

**Comment by jans23** [comment]
Thanks.

**Comment by bleckers** [comment]
Ah, just quickly, you will also have to run as root, or give read/write access to the serial port to your user.

So either:

sudo mono PortMuxRTool.exe

or:
chmod 777 /dev/ttyUSB0; mono PortMuxRTool.exe

**Comment by jans23** [comment]
I tried already (without mentioning it) but it doesn't help. Even sudo doesn't help.

**Comment by bleckers** [comment]
So according to the stack trace, it spits out a "System.IOException: Inappropriate ioctl for device" error.
Changing the serial port settings manually with stty doesn't fix this.

I am currently still looking and will post any updates as I go.

**Comment by bleckers** [comment]
Turns out there was a typo in the serial port setting code. The BaudRate was set to 56700 rather than 57600 (hence the ioctl error as it's an unsupported speed). I have pushed this change.
Now it's getting a timeout error which looks to be related to this issue - https://github.com/mono/mono/issues/10436

**Comment by bleckers** [comment]
That is now fixed and the changes are pushed. There is still an issue where the board is being reset by the DTR line being toggled on port open under Linux. The PortMuxRTool code sets DTR toggle to disabled, but it seems to be ignored under Linux (Mono running on Windows is fine).

Manually disabling DTR doesn't seem to work under Ubuntu with the following command either:
stty -F /dev/ttyUSB0 -hupcl

There is a "hard" work around for this and that's to cut the small trace between the DTR pads on the board, which disables the DTR reset functionality. However you will have to either resolder the pads together when you want to upgrade the firmware, or you will have to hit the reset button during the programming routine in Arduino.

![cut](https://user-images.githubusercontent.com/12459597/63207899-494e8c00-c111-11e9-8ba8-372e2bfefeee.png)

I'll try and get this sorted with a soft method though. Continue to leave it with me.

**Comment by bleckers** [comment]
The DTR issue can be solved by modifying the usb-serial kernel module. It's a known "issue" in the Linux kernel for most Arduino devices, hence why the PortMuxR boards have the ability to easily cut the DTR trace on the boards (this should also be cut in "industrial" situations where you don't want this to trigger accidentally). I have included some brief instructions on how to do this in the readme - https://github.com/SensorDots/PortMuxRTool/blob/master/README.md

**Comment by jans23** [comment]
Thank you for your fast help.
-- 
Sent from a mobile device.

**Comment by bleckers** [comment]
I just updated the readme with a quicker method of building just the kernel module required.
