### ISSUE TITLE
Scaling issue on small screen

### ISSUE THREAD

**Issue by jans23** [SensorDots/PortMuxRTool#2]
Because of issue #1 I tried PortMuxRTool on native Windows 10 in a virtual machine. By default the VM uses a relatively small screen. That seems to have the effect that PortMuxRTool's screen sections at the right are too narrow and barely readable. I can't resize PortMuxRTool's window which seems to be a fixed size and I can't change the section sizes within the window itself.

**Comment by bleckers** [comment]
This should hopefully be suitably fixed for smaller monitors now.

![scale](https://user-images.githubusercontent.com/12459597/63182909-04860f00-c097-11e9-9948-3d1d3fd37cbe.png)
